[variables]
NODE_VERSION = "20.11.0"

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.build]
cmds = [
    "cd apps/web && npm ci",
    "cd apps/web && npx prisma generate", 
    "cd apps/web && npm run build"
]

[phases.start]
cmd = "cd apps/web && npm run start:prod"