[variables]
NODE_VERSION = "22.18.0"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.build]
cmds = [
    "npm ci",
    "npx prisma generate", 
    "npm run build"
]

[phases.start]
cmds = ["npm run start:prod"]