[variables]
NODE_VERSION = "20.11.0"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.build]
workDir = "/app/apps/web"
cmds = ["npm ci", "npx prisma generate", "npm run build"]

[phases.start]
workDir = "/app/apps/web"
cmds = ["npm start"]