# nixpacks.toml - Monorepo deployment configuration for Nixpacks v1.39.0+
[variables]
NODE_VERSION = "24"
NIXPACKS_NODE_VERSION = "24"

[phases.setup] 
nixPkgs = ["nodejs_24"]

[phases.build]
cmds = [
    "cd apps/web && npm ci",
    "cd apps/web && npx prisma generate", 
    "cd apps/web && npm run build"
]

[start]
cmd = "cd apps/web && npm start"