[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "curl"]

[phases.build]
cmds = ["cd apps/web && npm ci", "cd apps/web && npx prisma generate", "cd apps/web && npm run build"]

[phases.start]
cmd = "./start.sh"

[start]
cmd = "./start.sh"

[staticAssets]
"apps/web/public" = "/app/public"