# nixpacks.toml - Monorepo deployment configuration for Nixpacks v1.39.0+
[variables]
NODE_VERSION = "22"
NIXPACKS_NODE_VERSION = "22"

[phases.setup] 
nixpkgsArchive = '51ad838b03a05b1de6f9f2a0fffecee64a9788ee'

[phases.build]
cmds = [
    "cd apps/web && npm ci",
    "cd apps/web && npx prisma generate", 
    "cd apps/web && npm run build"
]

[start]
cmd = "cd apps/web && npm start"