[variables]
NODE_VERSION = "20.11.0"

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.build]
workDir = "/app/apps/web"
cmds = ["npm ci", "npx prisma generate", "npm run build"]

[start]
workDir = "/app/apps/web"
cmd = "npm start"