[variables]
NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.build]
cmds = [
  "cd apps/web && npm ci", 
  "cd apps/web && npx prisma generate", 
  "cd apps/web && npm run build"
]

[start]
cmd = "cd apps/web && npm run start:prod"

[staticAssets]
"apps/web/public" = "/app/public"